export const AuthLoginConstants={
    AUTH_LOGIN_REQUEST:"LOGIN_REQUEST",
    AUTH_LOGIN_SUCCESS:"LOGIN_SUCCESS",
    AUTH_LOGIN_FAIL:"LOGIN_FAIL",
    AUTH_CLEAR_ERRORS:' AUTH_CLEAR_ERRORS'
}

export const AuthRegisterConstants={
    AUTH_REGISTER_REQUEST:" AUTH_REGISTER_REQUEST",
    AUTH_REGISTER_SUCCESS:"AUTH_REGISTER_SUCCESS",
    AUTH_REGISTER_FAIL:"AUTH_REGISTER_FAIL",
    AUTH_CLEAR_ERRORS:' AUTH_CLEAR_ERRORS'
}

export const GetProductsConstants={
    GET_ALL_PRODUCTS_REQUEST:" GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAIL:"GET_ALL_PRODUCTS_FAIL",


    GET_SINGLE_PRODUCT_REQUEST:" GET_SINGLE_PRODUCT_REQUEST",
    GET_SINGLE_PRODUCT_SUCCESS:"GET_SINGLE_PRODUCT_SUCCESS",
    GET_SINGLE_PRODUCT_FAIL:"GET_SINGLE_PRODUCT_FAIL",

    
    ADD_SINGLE_PRODUCT_REQUEST:" ADD_SINGLE_PRODUCT_REQUEST",
    ADD_SINGLE_PRODUCT_SUCCESS:"ADD_SINGLE_PRODUCT_SUCCESS",
    ADD_SINGLE_PRODUCT_FAIL:"ADD_SINGLE_PRODUCT_FAIL",

    
    PRODUCTS_CLEAR_ERRORS:'PRODUCTS_CLEAR_ERRORS',
}

export const ReviewConstants={
    PRODUCTS_REVIEW_REQUEST:" PRODUCTS_REVIEW_REQUEST",
    PRODUCTS_REVIEW_SUCCESS:"PRODUCTS_ REVIEW_SUCCESS",
    PRODUCTS_REVIEW_FAIL:"PRODUCTS_REVIEW_FAIL"
}

export const OrdersConstants={
    ORDERS_REQUEST:" ORDERS_REQUEST",
    ORDERS_SUCCESS:"ORDERS_SUCCESS",
    ORDERS_FAIL:"ORDERS_FAIL"
}

export const CLEAR_ERRORS='CLEAR_ERRORS'